"""生成给 GPT 的建模报告: 参数表 + 关键比例 + 自检结论。"""
import sys, os, math, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def build():
    import bridge_geom as G
    b = G.build_body_bm(); xs = [v.co.x for v in b.verts]
    v = G.build_voussoir_bm()
    d, l, p = G.build_deck_bm()
    be = G.build_beast_bm()
    tot = sum(G.SPANS) + G.N_SPAN*G.PIER_W + 2*G.BRIDGE_ABUT
    R = []
    R.append("## 当前 Blender 模型参数（自动生成 %s）\n" % "2026-10-04")
    R.append("### 官方/外部锚点（已锁定）\n")
    R.append("| 项 | 值 | 来源 |")
    R.append("|---|---|---|")
    R.append("| 桥全长 | 150 m | 官方 |")
    R.append("| 孔数 | 17，第9孔最大 | 官方 |")
    R.append("| 桥面下宽 | 14.6 m | 北京市公园管理中心 |")
    R.append("| 桥面上宽 | 6.56 m | 同上 |")
    R.append("| 桥高 | 7 m | 同上 |")
    R.append("| 望柱 | 128 根 | 官方资料 |")
    R.append("| 石狮 | 544 只 | 官方资料 |")
    R.append("| 桥头大型石兽 | 4 只 | 官方 |")
    R.append("| 券圈径向厚 | 0.40 m | 二级资料 |")
    R.append("| 桥墩厚 | 2.5 m | 二级资料 |")
    R.append("| 中央孔净跨 | 8.5 m | 北航《现代物理知识》光学建模文 |")
    R.append("| 端孔净跨 | 4.2~4.5 m | 同上/另一二级资料 |")
    R.append("")
    R.append("### 模型实际值\n")
    R.append("| 项 | 值 |")
    R.append("|---|---|")
    R.append("| 桥长（几何闭合） | %.4f m |" % (max(xs)-min(xs)))
    R.append("| 累计排布总长 | %.4f m |" % tot)
    R.append("| 缩放系数 K | %.4f（调和 8.5/4.5 与官方 150m） |" % G.K_SPAN)
    R.append("| 中央孔净跨 | %.3f m |" % G.SPANS[8])
    R.append("| 端孔净跨 | %.3f m |" % G.SPANS[0])
    R.append("| 端/中 比 | %.3f |" % (G.SPANS[0]/G.SPANS[8]))
    R.append("| 桥墩厚 | %.3f m |" % G.PIER_W)
    R.append("| 券圈径向厚 | %.3f m |" % G.RING_T)
    R.append("| 券矢跨比 f/l | %.3f |" % G.ARCH_RATIO)
    R.append("| 起拱线高（水面起） | %.2f m ⚠工作假设 |" % G.SPRINGER)
    R.append("| 桥面两端 | %.2f m ⚠工作假设 |" % G.deck_z(75.0))
    R.append("| 桥面中央 | %.2f m ⚠工作假设 |" % G.deck_z(0.0))
    R.append("| 桥面起拱差 | %.2f m |" % (G.deck_z(0.0)-G.deck_z(75.0)))
    R.append("| 中央券顶 | %.2f m |" % (G.SPRINGER+G.SPANS[8]*G.ARCH_RATIO))
    R.append("| 中央桥腹厚 | %.2f m |" % (G.deck_z(0.0)-(G.SPRINGER+G.SPANS[8]*G.ARCH_RATIO+G.RING_T)))
    R.append("| 望柱 | %d 对 = %d 根（官方128） |" % (G.N_NEWEL+1, 2*(G.N_NEWEL+1)))
    R.append("| 券石块 | 17 孔 × %d 块楔形 |" % 13)
    R.append("| 网格量 | body %d / voussoir %d / deck %d / panel %d / lion %d / beast %d |"
             % (len(b.verts),len(v.verts),len(d.verts),len(p.verts),len(l.verts),len(be.verts)))
    R.append("")
    R.append("### 逐孔净跨（半边 1..9，右侧镜像）\n")
    R.append("孔: " + " ".join("%d:%.2f" % (i+1, s) for i, s in enumerate(G.SPANS)))
    R.append("")
    R.append("### 桥面母曲线采样 deck_z(x)\n")
    R.append("```")
    for x in range(-75, 76, 10):
        R.append("x=%+4d  z=%.2f" % (x, G.deck_z(float(x))))
    R.append("```")
    R.append("")
    R.append("### 我自检发现的疑点（请一并裁决）\n")
    R.append("1. 正交侧视里 **券石像盖在券洞上的馒头**，而不是券洞自身的券圈。券圈应沿洞口轮廓，且券洞下方要有实体承托。")
    R.append("2. 正交侧视里 **桥面起伏几乎不可见**，两端未明显下降。矢高 4.4m/150m = 1/34，是否本该如此平缓？")
    R.append("3. 券洞在起拱线以下的部分是**悬空的**，墩只做到 SPRINGER。真实石桥券洞下应有墙体。")
    R.append("4. 望柱密度 50 对=100 根 < 官方 128 根；狮子在平视图里几乎看不见。")
    R.append("5. 起拱线 1.0m、桥面两端 2.6m/中央 7.0m 均为我的**工作假设**（官方只说“桥高7米”，未说基准）。")
    R.append("")
    R.append("请给出：\n")
    R.append("- 上述 5 点哪些是硬错？具体该怎么改（给数值）？\n")
    R.append("- 你认为**优先修哪三处**，按对“像十七孔桥”的贡献排序？\n")
    R.append("- 中央孔的 f/l 你建议取多少？（无实测的话给一个有依据的推断，并说明依据）\n")
    R.append("- 券石块数、望柱数、石狮造型，下一步该怎么排优先级？")
    return "\n".join(R)

if __name__ == "__main__":
    t = build()
    open("/Volumes/macstudio/video-projects/e30_shikongqiao_video/3d/refs/model_report.md","w",encoding="utf-8").write(t)
    print(t)
